// Session Persistance module is used for handling the persistance of the session keys that
// which are derieved from the ibsodium lib to be stored securely and used whenever required for the session management of the user in the FileBox application.


// ----------------------------------------ALGORITHMIC APPROCH GONNA USED--------------------------------------------------------
//1, First we decrypt our keys using the KEK generated by the password
//2, at the same time, using the native crypto module of browser we generate a session wrapper key
//3, using that wrapper key provide another layer of encryption over our decrypted keys
//4, store the native crypto encrypted keys + the session crypto key in the indexed DB with marking session key as extractable: false
//5,whenever user pulls out a refresh, using the indexed DB function we get the session key and decrypt the encrypted blob  that is 
// stored in the indexed DB

//Documenting some things here in the code so that i can sort of revise , revisit ect, for understanding the code in future.


import { fileBoxSessionDB } from './sessionDB'


export async function persistSessionKeys(
    masterKey: Uint8Array,
    privateKey: Uint8Array
): Promise<void> {

    //FIRST STEP IS TO CREATE A SESSION WRAPPER KEY USING THE NATIVE CRYPTO MODULE OF BROWSER
    const sessionWrapperKey = await window.crypto.subtle.generateKey(
        { name: "AES-GCM", length: 256 },
        false, // not extractable since we have to store it in the indexed DB and we don't want it to be extractable
        ["encrypt", "decrypt"] // gives the permission to encrypt and decrypt using this key
    );

    //Now we have to prepare the data to be encrypted with the session wrapper key.
    // we have to bundle the Uint8Array but its not possible in js directly so , we convert them into standert object and convert them into json string and then convert them into Uint8Array and then encrypt it with the session wrapper key

    const dataToEncrypt = JSON.stringify({
        masterKey: Array.from(masterKey),
        privateKey: Array.from(privateKey)
    }) // stringified object of the keys to encypt

    //Now we have to convert the stringified object into Uint8Array so that we can encrypt it with the session wrapper key
    const dataToEncryptUint8Array = new TextEncoder().encode(dataToEncrypt);

    // Next we have to generate the random nonce for the AES-GCM encryption so that we get unique ciphertext for the same plaintext every time we encrypt it 
    const iv = window.crypto.getRandomValues(new Uint8Array(12)); // 12 bytes random nonce for AES-GCM encryption

    // next we have to encrypt the data with the session key using the IV generated above and the session wrapper key generated above

    const encryptedDataCyhperText = await window.crypto.subtle.encrypt(
        { name: "AES-GCM", iv: iv },
        sessionWrapperKey,
        dataToEncryptUint8Array
    );

    // Now we have to store the encrypted data and the session wrapper key in the indexed DB using the Dexie DB instance created in the sessionDB.ts file
    await fileBoxSessionDB.securityKeySessionDB.put({
        id: "sessionWrapperKey", // we can use any unique id for the session wrapper key
        payload: sessionWrapperKey
    })
    await fileBoxSessionDB.securityKeySessionDB.put({
        id: "encryptedSessionData", // we can use any unique id for the encrypted data
        payload: {
            ciphertext: encryptedDataCyhperText,
            iv: iv
        }
    })

}


// Next we have to create a function to get the session keys from the indexed DB and decrypt them using the session wrapper key stored in the indexed DB

export async function restoreSessionKeys(): Promise<{ masterKey: Uint8Array, privateKey: Uint8Array } | null> {
    // first we need to get the stored keys from the DB
    try {

        const wrappingKey = await fileBoxSessionDB.securityKeySessionDB.get("sessionWrapperKey");
        const encryptedblob = await fileBoxSessionDB.securityKeySessionDB.get("encryptedSessionData");

        if (!wrappingKey || !encryptedblob) {
            // which means the indexed db session is wipped out, so we have to redirect to login
            console.log("Session keys not found in indexed DB"); //TESTING PURPOSE
            return null; // if we don't have the session wrapper key or the encrypted data in the indexed DB then we return null
        }

        // NEXT WE HAVE TO DECRYPT THE encryptedblob.ciphertext USING THE WRAPPING KEY AND THE IV STORED IN THE encryptedblob.iv

        const sessionKey = wrappingKey.payload as CryptoKey; // typecasting the payload to CryptoKey
        const { ciphertext, iv } = encryptedblob.payload as { ciphertext: ArrayBuffer, iv: any }; // typecasting the payload to the correct type


        const decryptedData = await window.crypto.subtle.decrypt(
            { name: "AES-GCM", iv: iv },
            sessionKey,
            ciphertext
        );

        // the stored encrypted data is a merged Uint8Array of the masterKey and privateKey so we have to split them back into two separate Uint8Arrays

        const decodedDecryptedData = new TextDecoder().decode(decryptedData); // convert the decrypted data back to string
        const parsedDecryptedData = JSON.parse(decodedDecryptedData); // parse the string back to object

        const restoredMasterKey = new Uint8Array(parsedDecryptedData.masterKey); // convert the masterKey back to Uint8Array
        const restoredPrivateKey = new Uint8Array(parsedDecryptedData.privateKey); // convert the privateKey back to Uint8Array

        return {
            masterKey: restoredMasterKey,
            privateKey: restoredPrivateKey
        }


    }
    catch (error) {
        console.error('Failed to restore session via Dexie:', error);
        await clearSessionKeys();
        return null;
    }


}

export async function clearSessionKeys(): Promise<void> {
  await fileBoxSessionDB.securityKeySessionDB.clear();  // this function is used to clear the session keys from the indexed DB when the user logs out or when the session expires
}