name : CI - CD PIPELINE

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v5
  
      - name: Set up Node js
        uses: actions/setup-node@3
        with:
            node-version: 20
      
      - name: Install dependencies
        run: npm install
  
      - name: Run tests
        run: npm test



   